package com.pragma.hogar360.serviceshome.infrastructure.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the Category entity for database persistence.
 * This class maps to the 'category' table in the database.
 */
@Entity
@Table(name = "category")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CategoryEntity {

    /**
     * The unique identifier for the category.
     * This field is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the category.
     * This field is mapped to the 'name' column in the database.
     * It is required, has a maximum length of 50 characters, and must be unique.
     */
    @Column(nullable = false, length = 50, unique = true)
    private String name;

    /**
     * The description of the category.
     * This field is mapped to the 'description' column in the database.
     * It is required and has a maximum length of 90 characters.
     */
    @Column(nullable = false, length = 90)
    private String description;

}